services:

  # RABBITMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cine-network

  # PELICULAS
  peliculas-app:
    build: ../peliculas-backend
    container_name: peliculas-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://peliculas-db:5432/peliculas_db
      SPRING_DATASOURCE_USERNAME: user_peliculas
      SPRING_DATASOURCE_PASSWORD: pass_peliculas
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:9090/realms/cinecloud
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/cinecloud/protocol/openid-connect/certs
      HISTORIAL_BASE_URL: http://historial-app:8083
      TZ: America/Argentina/Buenos_Aires
      JAVA_TOOL_OPTIONS: "-Duser.timezone=America/Argentina/Buenos_Aires"
    depends_on:
      - peliculas-db
      - rabbitmq
    networks:
      - cine-network

  peliculas-db:
    image: postgres:16
    container_name: peliculas-db-container
    environment:
      POSTGRES_DB: peliculas_db
      POSTGRES_USER: user_peliculas
      POSTGRES_PASSWORD: pass_peliculas
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5432:5432"
    volumes:
      - peliculas-data:/var/lib/postgresql/data
    networks:
      - cine-network

  # CARRITO
  carrito-app:
    build: ../carrito-backend
    container_name: carrito-app-container
    ports:
      - "8082:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://carrito-db:5432/carrito_db
      SPRING_DATASOURCE_USERNAME: user_carrito
      SPRING_DATASOURCE_PASSWORD: pass_carrito
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:9090/realms/cinecloud
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/cinecloud/protocol/openid-connect/certs
      PELICULAS_BASE_URL: http://peliculas-app:8080
      TZ: America/Argentina/Buenos_Aires
      JAVA_TOOL_OPTIONS: "-Duser.timezone=America/Argentina/Buenos_Aires"
    depends_on:
      - carrito-db
      - peliculas-app
      - rabbitmq
    networks:
      - cine-network

  carrito-db:
    image: postgres:16
    container_name: carrito-db-container
    environment:
      POSTGRES_DB: carrito_db
      POSTGRES_USER: user_carrito
      POSTGRES_PASSWORD: pass_carrito
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5433:5432"
    volumes:
      - carrito-data:/var/lib/postgresql/data
    networks:
      - cine-network

  # KEYCLOAK
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-container
    command: >
      start-dev
          --import-realm
          --spi-theme-cache-themes=false
          --spi-theme-cache-templates=false
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak_db
      KC_DB_USERNAME: user_keycloak
      KC_DB_PASSWORD: pass_keycloak
      TZ: America/Argentina/Buenos_Aires
      JAVA_TOOL_OPTIONS: "-Duser.timezone=America/Argentina/Buenos_Aires"
    ports:
      - "9090:8080"
    depends_on:
      - keycloak-db
    volumes:
      - ../keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ../keycloak/themes:/opt/keycloak/themes
    networks:
      - cine-network

  keycloak-db:
    image: postgres:16
    container_name: keycloak-db-container
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: user_keycloak
      POSTGRES_PASSWORD: pass_keycloak
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    networks:
      - cine-network

  # HISTORIAL DE COMPRAS
  historial-db:
    image: mongo:8
    container_name: historial-db-container
    ports:
      - "27017:27017"
    environment:
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - historial-data:/data/db
    networks:
      - cine-network

  historial-app:
    build: ../historial-compras-backend
    container_name: historial-app-container
    ports:
      - "8083:8083"
    environment:
      SPRING_DATA_MONGODB_HOST: historial-db
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: historial_db
      TZ: America/Argentina/Buenos_Aires
      JAVA_TOOL_OPTIONS: "-Duser.timezone=America/Argentina/Buenos_Aires"
    depends_on:
      - historial-db
      - rabbitmq
    networks:
      - cine-network

  # RATING
  rating-db:
    image: postgres:16
    container_name: rating-db-container
    environment:
      POSTGRES_DB: rating_db
      POSTGRES_USER: user_rating
      POSTGRES_PASSWORD: pass_rating
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5435:5432"
    volumes:
      - rating-data:/var/lib/postgresql/data
    networks:
      - cine-network

  rating-app:
    build: ../rating-backend
    container_name: rating-app-container
    ports:
      - "8086:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rating-db:5432/rating_db
      SPRING_DATASOURCE_USERNAME: user_rating
      SPRING_DATASOURCE_PASSWORD: pass_rating
      TZ: America/Argentina/Buenos_Aires
      JAVA_TOOL_OPTIONS: "-Duser.timezone=America/Argentina/Buenos_Aires"
    depends_on:
      - rating-db
    networks:
      - cine-network

  # NOTIFICACIONES
  notificaciones-app:
    build: ../notificaciones-backend
    container_name: notificaciones-app-container
    ports:
      - "8085:8085"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      APP_RABBITMQ_EXCHANGE: compra.exchange
      APP_RABBITMQ_ROUTING_KEY: compra.event
      APP_RABBITMQ_QUEUE: compras.notificaciones.queue
      MAILTRAP_USERNAME: ${MAILTRAP_USERNAME:-277e75063f7bfb}
      MAILTRAP_PASSWORD: ${MAILTRAP_PASSWORD:-d2e44d7a19b857}
      TZ: America/Argentina/Buenos_Aires
      JAVA_TOOL_OPTIONS: "-Duser.timezone=America/Argentina/Buenos_Aires"
    depends_on:
      - rabbitmq
    networks:
      - cine-network

volumes:
  peliculas-data:
  carrito-data:
  keycloak-data:
  historial-data:
  rating-data:

networks:
  cine-network:
